/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['"Plus Jakarta Sans"', 'ui-sans-serif', 'system-ui', 'sans-serif'],
      },
      colors: {
        'primary': '#3525cd',
        'on-primary': '#ffffff',
        'primary-container': '#4f46e5',
        'on-primary-container': '#dad7ff',
        'primary-fixed': '#e2dfff',
        'primary-fixed-dim': '#c3c0ff',
        'on-primary-fixed': '#0f0069',
        'on-primary-fixed-variant': '#3323cc',
        'inverse-primary': '#c3c0ff',
        'secondary': '#536600',
        'on-secondary': '#ffffff',
        'secondary-container': '#c6f000',
        'on-secondary-container': '#566a00',
        'secondary-fixed': '#c8f300',
        'secondary-fixed-dim': '#afd500',
        'on-secondary-fixed': '#171e00',
        'on-secondary-fixed-variant': '#3e4c00',
        'tertiary': '#7b3300',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#a04500',
        'on-tertiary-container': '#ffd2bd',
        'tertiary-fixed': '#ffdbca',
        'tertiary-fixed-dim': '#ffb690',
        'on-tertiary-fixed': '#341100',
        'on-tertiary-fixed-variant': '#783200',
        'error': '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'surface': '#f8f9ff',
        'surface-dim': '#cbdbf5',
        'surface-bright': '#f8f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#eff4ff',
        'surface-container': '#e5eeff',
        'surface-container-high': '#dce9ff',
        'surface-container-highest': '#d3e4fe',
        'surface-variant': '#d3e4fe',
        'surface-tint': '#4d44e3',
        'on-surface': '#0b1c30',
        'on-surface-variant': '#464555',
        'inverse-surface': '#213145',
        'inverse-on-surface': '#eaf1ff',
        'outline': '#777587',
        'outline-variant': '#c7c4d8',
        'background': '#f8f9ff',
        'on-background': '#0b1c30',
      },
      fontSize: {
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em' }],
        'headline-lg-mobile': ['28px', { lineHeight: '36px' }],
        'headline-md': ['24px', { lineHeight: '32px' }],
        'body-lg': ['18px', { lineHeight: '28px' }],
        'body-md': ['16px', { lineHeight: '24px' }],
        'body-sm': ['14px', { lineHeight: '20px' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.05em' }],
      },
    },
  },
  plugins: [],
};
